name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - name: Download MKL
        run: curl -sfO https://registrationcenter-download.intel.com/akdlm/IRC_NAS/18723/w_onemkl_p_2022.1.0.192.exe
      - name: Install MKL
        run: ./w_onemkl_p_2022.1.0.192.exe --a --silent --eula=accept